apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-io
  labels:
    app: istio-io
    version: v1
spec:
  replicas: 2
  # selector defaults to template's labels
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: istio-io
        version: v1
    spec:
      terminationGracePeriodSeconds: 5
      volumes:
      - name: nginx
        configMap:
          name: nginx
          # Map all keys to files.
      - name: certs
        secret:
          secretName: istio-io-tls
          # Map all keys to files.
      - name: cache
        emptyDir: {}
      containers:
      - name: nginx
        image: nginx:1.13.0-alpine  # = :mainline-alpine as of 2017/4/25
        resources:
         limits:
           cpu: 1
           memory: 512Mi
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /_healthz
            port: 80
            httpHeaders:
              - name: Host
                value: istio.io
          initialDelaySeconds: 3
          timeoutSeconds: 2
          failureThreshold: 2
        volumeMounts:
        - name: nginx
          mountPath: /etc/nginx
          readOnly: true
        - name: certs
          mountPath: /certs
          readOnly: true
        - name: cache
          mountPath: /cache
          readOnly: false
