# TODO: parametrize the parent directory yaml and/or keep in sync when
# succesfully experimenting here / on -stage sites
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-stage
  namespace: istio-system
spec:
  acme:
    # The ACME server URL
    server: https://acme-v01.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: ldemailly@google.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-stage-secret
    # Enable the HTTP-01 challenge provider
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: fortio-cert-stage
  namespace: istio-system
spec:
  secretName: istio-ingress-certs
  issuerRef:
    name: letsencrypt-stage
  commonName: fortio-stage.istio.io
  dnsNames:
  - fortio-stage.istio.io
  - istio-stage.fortio.org
  acme:
    config:
    - http01:
        # This class doesn't exist on purpose so we'll use the less specific
        # istio ingress one because we need the auth off annotation on the svc
        ingressClass: not-there
      domains:
      - fortio-stage.istio.io
      - istio-stage.fortio.org
---
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-ingress1
  namespace: istio-system
  annotations:
    auth.istio.io/8089: NONE
spec:
  ports:
  - port: 8089
    name: http-certingr
  selector:
    certmanager.k8s.io/domain: fortio-stage.istio.io
---
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-ingress2
  namespace: istio-system
  annotations:
    auth.istio.io/8089: NONE
spec:
  ports:
  - port: 8089
    name: http-certingr
  selector:
    certmanager.k8s.io/domain: istio-stage.fortio.org
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
    certmanager.k8s.io/acme-challenge-type: http01
    certmanager.k8s.io/issuer: letsencrypt-stage
# not working:
#    kubernetes.io/ingress.global-static-ip-name: fortio-stage-ip
  name: istio-ingress-certs-mgr
  namespace: istio-system
spec:
  rules:
  - http:
      paths:
        # cert-manager adds its own rules to the ingress but we need our
        # rule because we have to selectively disable auth for the service
        # and route to the service and not a nodeport
      - path: /.well-known/acme-challenge/.*
        backend:
          serviceName: cert-manager-ingress1
          servicePort: http-certingr
    # Unfortunately host isn't an array and there are no "*" allowed for all
    host: fortio-stage.istio.io
  - http:
      paths:
      - path: /.well-known/acme-challenge/.*
        backend:
          serviceName: cert-manager-ingress2
          servicePort: http-certingr
    host: istio-stage.fortio.org
