---
# cluster-issuer
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  namespace: default
  # Adjust the name here accordingly
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: jasonyoung@google.com
    # Name of a secret used to store the ACME account private key from step 3
    privateKeySecretRef:
      name: letsencrypt-private-key
    dns01:
      providers:
      - name: clouddns
        clouddns:
          serviceAccountSecretRef:
            name: clouddns
            key: clouddns.key.json
          project: istio-io

