apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: istio-io
  namespace: default
spec:
  secretName: istio-io-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: '*.istio.io'
  dnsNames:
  - istio.io
  acme:
    config:
    - dns01:
        provider: clouddns
      domains:
      - '*.istio.io'
      - istio.io
